# Generated by Django 5.1.5 on 2025-08-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='المعرف (Slug)')),
            ],
            options={
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الوسم')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='المعرف (Slug)')),
            ],
            options={
                'verbose_name_plural': 'الوسوم',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقالة')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='المعرف (Slug)')),
                ('content', models.TextField(verbose_name='محتوى المقالة')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images/', verbose_name='صورة المقالة')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المؤلف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='custom_articles.category', verbose_name='التصنيف')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='custom_articles.tag', verbose_name='الوسوم')),
            ],
            options={
                'verbose_name': 'مقالة',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('body', models.TextField(verbose_name='التعليق')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='custom_articles.article', verbose_name='المقالة')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created'],
            },
        ),
    ]
